pipeline:
  name: GreenInstallers
  host: go01.thoughtworks.com
  protocol: https
  port: 443
  stage: defaultStage
message: since last green installer
mood_cutoffs_in_minutes:
  enraged: 1440
  angry: 1080
  neutral: 120
